sudo: false

cache:
  directories:
    - $HOME/.composer/cache

language: php

env:
  global:
    - COVERAGE=0 XDEBUG=0

matrix:
  include:
    - php: 7.1
      env: LARAVEL='5.5.*'
    - php: 7.1
      env: LARAVEL='5.6.*'
    - php: 7.1
      env: LARAVEL='5.7.*'
    - php: 7.2
      env: LARAVEL='5.5.*'
    - php: 7.2
      env: LARAVEL='5.6.*'
    - php: 7.2
      env: LARAVEL='5.7.*'
    - php: 7.3
      env: LARAVEL='5.5.*' XDEBUG=1
    - php: 7.3
      env: LARAVEL='5.6.*' XDEBUG=1
    - php: 7.3
      env: COVERAGE=1 LARAVEL='5.7.*' XDEBUG=1
  fast_finish: true


before_install:
  - if [[ $XDEBUG = 0 ]]; then phpenv config-rm xdebug.ini; fi
  - travis_retry composer self-update
  - travis_retry composer require "illuminate/contracts:${LARAVEL}" --no-interaction --no-update

install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

script:
  - if [[ $COVERAGE = 1 ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml; fi
  - if [[ $COVERAGE = 0 ]]; then vendor/bin/phpunit --colors=always --verbose; fi

after_success:
  - if [[ $COVERAGE = 1 ]]; then bash <(curl -s https://codecov.io/bash); fi
