stages:
  - lint
  - test
  - coverage
  - bench

before_install:
  - phpenv config-rm xdebug.ini || true
  - echo "memory_limit=4G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - mysql -e 'CREATE DATABASE test;'

install:
  - composer require "illuminate/contracts:${LARAVEL}" --no-interaction --prefer-dist --no-interaction --no-suggest

script: vendor/bin/phpunit --colors=always --verbose

jobs:
  fast_finish: true
  allow_failures:
    - stage: coverage
    - stage: bench
  include:
    - stage: lint
      php: "7.3"
      env: LARAVEL='^6.0'
      script:
        - composer stan
        - composer normalize --dry-run
    - stage: test
      php: "7.1"
      env: LARAVEL='5.5.*'
    - php: "7.1"
      env: LARAVEL='5.6.*'
    - php: "7.1"
      env: LARAVEL='5.7.*'
    - php: "7.1"
      env: LARAVEL='5.8.*'
    - php: "7.2"
      env: LARAVEL='5.5.*'
    - php: "7.2"
      env: LARAVEL='5.6.*'
    - php: "7.2"
      env: LARAVEL='5.7.*'
    - php: "7.2"
      env: LARAVEL='5.8.*'
    - php: "7.2"
      env: LARAVEL='^6.0'
    - php: "7.3"
      env: LARAVEL='5.5.*'
    - php: "7.3"
      env: LARAVEL='5.6.*'
    - php: "7.3"
      env: LARAVEL='5.7.*'
    - php: "7.3"
      env: LARAVEL='5.8.*'
    - php: "7.3"
      env: LARAVEL='^6.0'
    - stage: coverage
      php: "7.3"
      env: LARAVEL='^6.0'
      script:
        - phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml
        - bash <(curl -s https://codecov.io/bash)
    - stage: bench
      php: "7.3"
      env: LARAVEL='^6.0'
      script:
        - vendor/bin/phpbench run --progress=none --report=ast

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache

language: php
