sudo: false

cache:
  directories:
  - $HOME/.composer/cache

language: php

php:
- 7.0
- 7.1
- 7.2

env:
  matrix:
  - LARAVEL='5.4.*' PHPUNIT='~5.7'
  - LARAVEL='5.5.*' PHPUNIT='~6.0'
  - LARAVEL='5.6.*' PHPUNIT='^7.0'
  - LARAVEL='5.7.*' PHPUNIT='^7.0'
  global:
  - COVERAGE=0

matrix:
  exclude:
  - php: 7.0
    env: LARAVEL='5.6.*' PHPUNIT='^7.0'
  - php: 7.0
    env: LARAVEL='5.7.*' PHPUNIT='^7.0'
  - php: 7.2
    env: LARAVEL='5.7.*' PHPUNIT='^7.0'
  include:
  - php: 7.2
    env: LARAVEL='5.7.*' PHPUNIT='^7.0' COVERAGE=1
  fast_finish: true

before_install:
- phpenv config-rm xdebug.ini
- composer global require hirak/prestissimo --update-no-dev
- composer require
  "illuminate/contracts:${LARAVEL}"
  "illuminate/http:${LARAVEL}"
  "illuminate/pagination:${LARAVEL}"
  "illuminate/routing:${LARAVEL}"
  "illuminate/support:${LARAVEL}"
  "illuminate/validation:${LARAVEL}"
  "orchestra/testbench:${LARAVEL/5\./3\.}"
  "orchestra/database:${LARAVEL/5\./3\.}"
  "phpunit/phpunit:${PHPUNIT}"
  --no-interaction --no-update

install:
- composer install --prefer-dist --no-interaction --no-suggest

script:
- if [[ $COVERAGE = 1 ]]; then
    phpdbg -qrr phpunit --colors=always --verbose --coverage-text --coverage-clover=coverage.xml;
  else
    phpunit --colors=always --verbose;
  fi

after_success:
- if [[ $COVERAGE = 1 ]]; then bash <(curl -s https://codecov.io/bash); fi
