version: '3.7'

services:
  php:
    build:
      context: .
      dockerfile: php.dockerfile
      args:
        USER: $USER
    volumes:
      - ./:/workdir
    security_opt:
      - label:disable
    depends_on:
      - mysql
    environment:
      XDEBUG_CONFIG: "remote_enable=1 remote_mode=req remote_port=9000 remote_connect_back=0 remote_host=host.docker.internal"
      PHP_IDE_CONFIG: "serverName=lighthouse"
    tty: true

  mysql:
    image: mysql:5.7
    tmpfs: /var/lib/mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  node:
    build:
      context: .
      dockerfile: node.dockerfile
    volumes:
      - ./docs:/app
    security_opt:
      - label:disable
    working_dir: /app
    environment:
      - NODE_OPTIONS="--max-old-space-size=8192"
    ports:
      - 8080:8080
    tty: true
