version: '2'

services:
  php:
    image: spawnia/php7.1-fpm:dev
    volumes:
      - ./:/var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:w+nUc1ZQlOX4JI4PfIp1TZORaju1JfAxnsJ0SLT1A+4=

      - DB_HOST=mysql
      - DB_USERNAME=root

  mysql:
    image: mysql:5.7
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
    environment:
      - MYSQL_DATABASE=lighthouse
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
