version: '2.2'

services:
  php:
    build: .
    image: lighthouse-php:base
    volumes:
    - ./:/var/www

  xdebug:
    build:
      context: .
      dockerfile: Dockerfile_xdebug
    image: lighthouse-php:xdebug
    environment:
      XDEBUG_CONFIG: "remote_enable=1 remote_mode=req remote_port=9000 remote_host=10.0.2.2 remote_connect_back=0"
      PHP_IDE_CONFIG: "serverName=lighthouse"
    volumes:
    - ./:/var/www

  node:
    image: node
    volumes:
    - ./docs:/app
    working_dir: /app
    ports:
    - 8080:8080
    command: bash -c "yarn && yarn docs:dev"
