version: '3.7'

services:
  php:
    build: .
    volumes:
    - ./:/var/www
    depends_on:
      - mysql
    environment:
      XDEBUG_CONFIG: "remote_enable=1 remote_mode=req remote_port=9000 remote_host=$XDEBUG_REMOTE_HOST remote_connect_back=0"
      PHP_IDE_CONFIG: "serverName=lighthouse"

  mysql:
    image: mysql:5.7
    tmpfs: /var/lib/mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  node:
    image: node:12
    volumes:
    - ./docs:/app
    working_dir: /app
    ports:
    - 8080:8080
    tty: true
